// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class EstadoOrdenTrabajo
{
    public int IdEstadoOrdenTrabajo { get; set; }

    public string Nombre { get; set; }

    public int Orden { get; set; }

    public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; } = new List<OrdenTrabajo>();

    public virtual ICollection<OrdenTrabajoEstadoHistorial> OrdenTrabajoEstadoHistorial { get; set; } = new List<OrdenTrabajoEstadoHistorial>();
}