// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class OrdenTrabajoServicio
{
    public int IdOrdenTrabajoServicio { get; set; }

    public int IdOrdenTrabajo { get; set; }

    public int? IdServicio { get; set; }

    public string NombreServicio { get; set; }

    public decimal Precio { get; set; }

    public int Cantidad { get; set; }

    public string Notas { get; set; }

    public virtual OrdenTrabajo IdOrdenTrabajoNavigation { get; set; }

    public virtual CatalogoServicio IdServicioNavigation { get; set; }
}