// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class OrdenTrabajoEstadoHistorial
{
    public int IdOrdenTrabajoEstadoHistorial { get; set; }

    public int IdOrdenTrabajo { get; set; }

    public int IdEstadoOrdenTrabajo { get; set; }

    public int IdUsuario { get; set; }

    public DateTime FechaCambio { get; set; }

    public string Comentario { get; set; }

    public virtual EstadoOrdenTrabajo IdEstadoOrdenTrabajoNavigation { get; set; }

    public virtual OrdenTrabajo IdOrdenTrabajoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}