// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class CatalogoServicio
{
    public int IdServicio { get; set; }

    public int IdTaller { get; set; }

    public string Nombre { get; set; }

    public decimal PrecioSugerido { get; set; }

    public bool Activo { get; set; }

    public virtual Taller IdTallerNavigation { get; set; }

    public virtual ICollection<OrdenTrabajoServicio> OrdenTrabajoServicio { get; set; } = new List<OrdenTrabajoServicio>();
}