// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public int IdTaller { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string Correo { get; set; }

    public string Identidad { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual Taller IdTallerNavigation { get; set; }

    public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; } = new List<OrdenTrabajo>();

    public virtual ICollection<VehiculoCliente> VehiculoCliente { get; set; } = new List<VehiculoCliente>();
}