// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class OrdenTrabajoAdjunto
{
    public int IdOrdenTrabajoAdjunto { get; set; }

    public int IdOrdenTrabajo { get; set; }

    public string UrlArchivo { get; set; }

    public string TipoArchivo { get; set; }

    public string Comentario { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual OrdenTrabajo IdOrdenTrabajoNavigation { get; set; }
}