// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class OrdenTrabajo
{
    public int IdOrdenTrabajo { get; set; }

    public int IdTaller { get; set; }

    public int IdCliente { get; set; }

    public int IdVehiculoCliente { get; set; }

    public int IdEstadoOrdenTrabajo { get; set; }

    public int? IdMecanicoAsignado { get; set; }

    public string MotivoIngreso { get; set; }

    public string Diagnostico { get; set; }

    public string Observaciones { get; set; }

    public DateTime FechaIngreso { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaListo { get; set; }

    public DateTime? FechaEntrega { get; set; }

    public decimal SubtotalManoObra { get; set; }

    public decimal OtrosCargos { get; set; }

    public decimal Descuento { get; set; }

    public bool Cerrada { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual EstadoOrdenTrabajo IdEstadoOrdenTrabajoNavigation { get; set; }

    public virtual Usuario IdMecanicoAsignadoNavigation { get; set; }

    public virtual Taller IdTallerNavigation { get; set; }

    public virtual VehiculoCliente IdVehiculoClienteNavigation { get; set; }

    public virtual ICollection<OrdenTrabajoAdjunto> OrdenTrabajoAdjunto { get; set; } = new List<OrdenTrabajoAdjunto>();

    public virtual ICollection<OrdenTrabajoEstadoHistorial> OrdenTrabajoEstadoHistorial { get; set; } = new List<OrdenTrabajoEstadoHistorial>();

    public virtual ICollection<OrdenTrabajoServicio> OrdenTrabajoServicio { get; set; } = new List<OrdenTrabajoServicio>();
}