// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class Taller
{
    public int IdTaller { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string WhatsApp { get; set; }

    public string Direccion { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual ICollection<CatalogoServicio> CatalogoServicio { get; set; } = new List<CatalogoServicio>();

    public virtual ICollection<Cliente> Cliente { get; set; } = new List<Cliente>();

    public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; } = new List<OrdenTrabajo>();

    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();

    public virtual ICollection<VehiculoCliente> VehiculoCliente { get; set; } = new List<VehiculoCliente>();
}