// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public int IdTaller { get; set; }

    public string Nombre { get; set; }

    public string UsuarioLogin { get; set; }

    public string Contrasena { get; set; }

    public string Telefono { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual Taller IdTallerNavigation { get; set; }

    public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; } = new List<OrdenTrabajo>();

    public virtual ICollection<OrdenTrabajoEstadoHistorial> OrdenTrabajoEstadoHistorial { get; set; } = new List<OrdenTrabajoEstadoHistorial>();

    public virtual ICollection<UsuarioRol> UsuarioRol { get; set; } = new List<UsuarioRol>();
}