// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class UsuarioRol
{
    public int IdUsuarioRol { get; set; }

    public int IdUsuario { get; set; }

    public int IdRol { get; set; }

    public bool Activo { get; set; }

    public virtual Rol IdRolNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}