// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTaller.Entities.Entities;

public partial class VehiculoCliente
{
    public int IdVehiculoCliente { get; set; }

    public int IdTaller { get; set; }

    public int IdCliente { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public int? Anio { get; set; }

    public string Placa { get; set; }

    public string VIN { get; set; }

    public string Color { get; set; }

    public int? Kilometraje { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Taller IdTallerNavigation { get; set; }

    public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; } = new List<OrdenTrabajo>();
}