// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SistemaTaller.Entities.Entities;

namespace SistemaTaller.DataAccess.SistemaTallerContext;

public partial class DbTallerContext : DbContext
{

    public DbTallerContext()
     
    {
    }


    public DbTallerContext(DbContextOptions<DbTallerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CatalogoServicio> CatalogoServicio { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<EstadoOrdenTrabajo> EstadoOrdenTrabajo { get; set; }

    public virtual DbSet<OrdenTrabajo> OrdenTrabajo { get; set; }

    public virtual DbSet<OrdenTrabajoAdjunto> OrdenTrabajoAdjunto { get; set; }

    public virtual DbSet<OrdenTrabajoEstadoHistorial> OrdenTrabajoEstadoHistorial { get; set; }

    public virtual DbSet<OrdenTrabajoServicio> OrdenTrabajoServicio { get; set; }

    public virtual DbSet<Rol> Rol { get; set; }

    public virtual DbSet<Taller> Taller { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }

    public virtual DbSet<VehiculoCliente> VehiculoCliente { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CatalogoServicio>(entity =>
        {
            entity.HasKey(e => e.IdServicio);

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.PrecioSugerido).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.IdTallerNavigation).WithMany(p => p.CatalogoServicio)
                .HasForeignKey(d => d.IdTaller)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CatalogoServicio_Taller");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente);

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Correo)
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.FechaActualizacion).HasColumnType("datetime");
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Identidad)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Observaciones)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.IdTallerNavigation).WithMany(p => p.Cliente)
                .HasForeignKey(d => d.IdTaller)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cliente_Taller");
        });

        modelBuilder.Entity<EstadoOrdenTrabajo>(entity =>
        {
            entity.HasKey(e => e.IdEstadoOrdenTrabajo);

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<OrdenTrabajo>(entity =>
        {
            entity.HasKey(e => e.IdOrdenTrabajo);

            entity.Property(e => e.Descuento).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Diagnostico)
                .HasMaxLength(800)
                .IsUnicode(false);
            entity.Property(e => e.FechaActualizacion).HasColumnType("datetime");
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.FechaEntrega).HasColumnType("datetime");
            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");
            entity.Property(e => e.FechaInicio).HasColumnType("datetime");
            entity.Property(e => e.FechaListo).HasColumnType("datetime");
            entity.Property(e => e.MotivoIngreso)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Observaciones)
                .HasMaxLength(800)
                .IsUnicode(false);
            entity.Property(e => e.OtrosCargos).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SubtotalManoObra).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.OrdenTrabajo)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OT_Cliente");

            entity.HasOne(d => d.IdEstadoOrdenTrabajoNavigation).WithMany(p => p.OrdenTrabajo)
                .HasForeignKey(d => d.IdEstadoOrdenTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OT_Estado");

            entity.HasOne(d => d.IdMecanicoAsignadoNavigation).WithMany(p => p.OrdenTrabajo)
                .HasForeignKey(d => d.IdMecanicoAsignado)
                .HasConstraintName("FK_OT_Mecanico");

            entity.HasOne(d => d.IdTallerNavigation).WithMany(p => p.OrdenTrabajo)
                .HasForeignKey(d => d.IdTaller)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OT_Taller");

            entity.HasOne(d => d.IdVehiculoClienteNavigation).WithMany(p => p.OrdenTrabajo)
                .HasForeignKey(d => d.IdVehiculoCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OT_Vehiculo");
        });

        modelBuilder.Entity<OrdenTrabajoAdjunto>(entity =>
        {
            entity.HasKey(e => e.IdOrdenTrabajoAdjunto);

            entity.Property(e => e.Comentario)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.TipoArchivo)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.UrlArchivo)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.IdOrdenTrabajoNavigation).WithMany(p => p.OrdenTrabajoAdjunto)
                .HasForeignKey(d => d.IdOrdenTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Adjunto_OT");
        });

        modelBuilder.Entity<OrdenTrabajoEstadoHistorial>(entity =>
        {
            entity.HasKey(e => e.IdOrdenTrabajoEstadoHistorial);

            entity.Property(e => e.Comentario)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.FechaCambio).HasColumnType("datetime");

            entity.HasOne(d => d.IdEstadoOrdenTrabajoNavigation).WithMany(p => p.OrdenTrabajoEstadoHistorial)
                .HasForeignKey(d => d.IdEstadoOrdenTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Hist_Estado");

            entity.HasOne(d => d.IdOrdenTrabajoNavigation).WithMany(p => p.OrdenTrabajoEstadoHistorial)
                .HasForeignKey(d => d.IdOrdenTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Hist_OT");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.OrdenTrabajoEstadoHistorial)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Hist_Usuario");
        });

        modelBuilder.Entity<OrdenTrabajoServicio>(entity =>
        {
            entity.HasKey(e => e.IdOrdenTrabajoServicio);

            entity.Property(e => e.NombreServicio)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.Notas)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.Precio).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.IdOrdenTrabajoNavigation).WithMany(p => p.OrdenTrabajoServicio)
                .HasForeignKey(d => d.IdOrdenTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OTS_OT");

            entity.HasOne(d => d.IdServicioNavigation).WithMany(p => p.OrdenTrabajoServicio)
                .HasForeignKey(d => d.IdServicio)
                .HasConstraintName("FK_OTS_Servicio");
        });

        modelBuilder.Entity<Rol>(entity =>
        {
            entity.HasKey(e => e.IdRol);

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Taller>(entity =>
        {
            entity.HasKey(e => e.IdTaller);

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Direccion)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.FechaActualizacion).HasColumnType("datetime");
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.WhatsApp)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario);

            entity.HasIndex(e => e.UsuarioLogin, "UQ__Usuario__F96234F35085DCC1").IsUnique();

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Contrasena)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FechaActualizacion).HasColumnType("datetime");
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UsuarioLogin)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false);

            entity.HasOne(d => d.IdTallerNavigation).WithMany(p => p.Usuario)
                .HasForeignKey(d => d.IdTaller)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_Taller");
        });

        modelBuilder.Entity<UsuarioRol>(entity =>
        {
            entity.HasKey(e => e.IdUsuarioRol);

            entity.Property(e => e.Activo).HasDefaultValue(true);

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.UsuarioRol)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioRol_Rol");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioRol)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioRol_Usuario");
        });

        modelBuilder.Entity<VehiculoCliente>(entity =>
        {
            entity.HasKey(e => e.IdVehiculoCliente);

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Color)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Marca)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.Modelo)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.Observaciones)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Placa)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.VIN)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.VehiculoCliente)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VehiculoCliente_Cliente");

            entity.HasOne(d => d.IdTallerNavigation).WithMany(p => p.VehiculoCliente)
                .HasForeignKey(d => d.IdTaller)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VehiculoCliente_Taller");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}